AllCops:
  Exclude:
    - vendor/**
    - metadata.rb

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
MethodCallParentheses:
  Enabled: false
WordArray:
  Enabled: false
