name             'dc_devfest'
maintainer       'Peter Burkholder'
maintainer_email 'pburkholder@getchef.com'
license          'Apache 2.0'
description      'Installs/Configures dc_devfest'
long_description 'Installs/Configures dc_devfest'
version          '0.2.5'

depends 'gce', '= 0.3.1'
depends 'pdb_motd'
